### ISSUE TITLE
MVP 제작 - 상품 컴포넌트

### ISSUE THREAD

**Issue by jihoon135** [minggichae/COUrse#4]
## Description
- 상품 컴포넌트 제작

## To-do
- [ ] Firebase 연결
- [ ] 상품 더미데이터 생성
- [ ] 상품 컴포넌트 제작
- [ ] 상품 더미데이터 컴포넌트에 추가

## Expected time
- ~07-05

## ETC
- Firebase api 값은 .env 파일(환경변수) 처리 예정

**Comment by minggichae** [comment]
내가 실험을 위해 임의로 json 파일을 하나 생성해서 더미데이터를 만들긴 했는데 보고 코멘트를 해주길 바람.

**Comment by minggichae** [comment]
회의를 통해 상품의 이미지가 더미 데이터를 모아놓는 json 형식에서 사용이 가능하다면 firebase를 사용하지 않을 예정임.
하지만, 이미지 사용이 불가능하다면 firebase를 활용하여 이미지를 노출할 예정임.
